### ISSUE TITLE
[epic] Dataset and Resource creation guide and interaction re metadata

### ISSUE THREAD

**Issue by rufuspollock** [datopian/tech.datopian.com#13]
Main work is to create a guide re metadata creation and automated metadata hinting / description/ validation.

When as a Python (or R) user I am creating datasets using Python (or R) I want documentation and/or feedback as part of the SDK detailing how to programmatically reference/add the appropriate metadata fields, both mandatory and optional, and especially metadata fields that populate dropdowns so that I can quickly create a valid dataset

## Job Stories

When I am creating a data flow in Python [R ...] to load data into my Hub / Catalog / Exchange I want

* a quick start guide I can read with code examples with examples for common tasks (e.g. creating a dataset, uploading a file)
* A reference of all the metadata fields and their usage / requirements (including enumerations)
* to create a code template with the key metadata fields set (with comments) in Python / R / Javascript
* (?) to create a template json (or yaml) file with key fields (so that other people can use that file)

So that I can quickly create datasets (including metadata) and upload data

## Domain Model

* Profile for *metadata*: spec for metadata for a Resource or Dataset i.e. what attributes it has, which are required, what possible values are allowed
* Schema for *data*: describes the fields in a Resource (e.g. columns in a tables) and which are required, their types etc

A given Hub could have one or more Profiles. For example, you might have a profile for genomics data and a profile for survey data.

See https://tech.datopian.com/glossary/ for more.

## Example

Example in R:

```R
# Mandatory Fields

# lowercase alphanumeric and underscores only
name = 'sample_r_dataset2'

# display name
title = 'Sample R Dataset'

notes = 'Detailed Dataset Description'

maintainer='Dataset Maintainer Name'

maintainer_email='Dataset.Maintainer@xxx.org'

publisher='Dataset Publisher'

owner_org='yyy'

visibility='public'
# other options: 'private'

geographic_level='global'
#other options: 'national','regional','sub-national','other'

license_id='notspecified'

information_classification= 'public-public-external'
# other options: 'not_sensitive-non_confidential-internal-business', 'not_sensitive-non_confidential-internal-business', etc
```

## Acceptance

* [ ] We have a quick start guide with Howtos for **See https://github.com/datopian/ckan-client-guide**
  * [ ] Creating a dataset in code with metadata
  * [x] Creating a dataset from a resource/file **https://github.com/datopian/ckan-client-guide#upload-a-resource-file-and-implicitly-create-a-new-dataset**
  * [x] Adding a resource/file to an existing dataset **https://github.com/datopian/ckan-client-guide#adding-a-resource-to-an-existing-dataset**
  * [ ] Editing an existing dataset's metadata **https://github.com/datopian/ckan-client-guide#edit-a-datasets-metadata**
  * [ ] Creating a dataset direct from metadata in a JSON file (yaml?)
* [ ] Reference doc in markdown for profile(s) in use (which can be automatically generated from profiles in json schema)
* [ ] We have a function to automatically generate a file with metadata that you can then fill in as per R example above (based on profile chosen) **IN PROGRESS see https://github.com/datopian/jsv**
  * [ ] Python
  * [ ] R
  * [ ] JS
  * [ ] JSON (Yaml?)
* [ ] (?) There is an interactive command line tool for doing that ...

## Tasks

* [x] Preparation: read about  (~2h)
  * [x] json schema https://json-schema.org/
  * [x] json schema validation 
  * [x] JSON schemas for frictionless specs e.g https://specs.frictionlessdata.io/schemas/data-package.json (you can find links to each on in the relevant spec doc on https://specs.frictionlessdata.io/)
* [ ] Creating an example client profile
  * [ ] Find an example profile for this client as defined in e.g. ckanext-scheming for Datasets and Resources
   * [ ] Convert to JSON schema and align with JSON schemas for Frictionless profiles (ie. base off those if you can)
* [ ] Auto-generate a reference doc for metadata profile datopian/ckan-client-guide#2
* [ ] Auto-generate code for metadata profile datopian/ckan-client-guide#3 
* [ ] Stub out a guide in markdown for a new developer with outline for the part where we create metadata **IN PROGRESS See current README for this project**
  * [ ] Make those parts actually work ...

### Stub out guide

* [ ] Outline howtos
* [ ] Think about what Frictionless lib we use

### JSON Schema

* JSON schema is for defining the structure of JSON data. By using the $schema keyword, you explicitly mention the schema.
* The fields of the JSON schema comes under the properties tag where you mention them individually and describe their type i.e. integar, string etc.
* You can also mention the required fields in the schema by mention the name of the properties that are compulsory.

### How client code should interact with CKAN / DataHub

* Use frictioness everywhere in the client up to point you push to CKAN
* The CKAN SDK provides conversion from Frictionless to CKAN API
  * In future, this may be built into CKAN itself (ie. CKAN speaks Frictionless natively)

```mermaid
graph LR

client[Client]
sdk[CKAN SDK ]
ckan[CKAN]

client --frictionless formats--> sdk
sdk --ckan format--> ckan
```

What this concretely means: creating metadata and manipulating it should follow Frictionless format and SDK then takes care of converting that to CKAN format.

Why?

* Frictionless formats are well defined and mature and widely used
* The client gets to use the rich, mature tooling around Frictionless formats
* Clean conversion over to CKAN
