### ISSUE TITLE
Auto generate a reference page for a Resource/Dataset profile

### ISSUE THREAD

**Issue by rufuspollock** [datopian/tech.datopian.com#14]
When I have a profile for my metadata (in json schema) I want to generate reference docs for it so that data scientists and data engineers in my team can get started quickly

## Acceptance

* [x] Given a profile in JSON Schema generate a reference doc in markdown or HTML (basic or nice - nice would be like image in https://github.com/frictionlessdata/forum/issues/49) **ANS: [`jsv`](https://github.com/datopian/jsv)**
* [ ] Have an embeddable js lib / script that lays this out (with css) file ... **WIP [`jsv`](https://github.com/datopian/jsv)**
* [ ] A mini app: paste your schema url and hey presto there's the documentation (and you can iframe to embed)

## Tasks

* [x] Choose whether we use JS or Python for the remaining work **ANS: probably JS**
* [x] Find a profile to work on **DONE: https://specs.frictionlessdata.io/schemas/data-resource.json**
* [x] Auto generate a reference page in markdown or html using JS or script **ANS [`jsv`](https://github.com/datopian/jsv)**
  * [ ] Add support for CSS file
* [ ] Publish `jsv` so it's `npm`-installable (does that make sense? cc @rufuspollock)

### Research libraries for viewing JSON schema in JS

See also https://github.com/frictionlessdata/forum/issues/49

* https://github.com/stoplightio/json-schema-viewer (49 ⭐) - Demo via storybook https://stoplightio.github.io/json-schema-viewer/
  * Very solid and polished. A little over fancy and interactive. We just want a simple doc (preferably static) and need full React to embed ...
  * Could we reuse some code ...
