### ISSUE TITLE
Auto generate "init" code for a Resource/Dataset profile

### ISSUE THREAD

**Issue by rufuspollock** [datopian/tech.datopian.com#15]
When I have a profile for my metadata (in json schema) I want to generate code templates to that data scientists and data engineers in my team can get started quickly

## Acceptance

* [x] A command line tool (or function in library) that given a profile in JSON Schema generate a template file similar to below (appropriate to language / format) **ANS [`jsv`](https://github.com/datopian/jsv)**
  * [x] Python
  * [x] R
  * [x] JS
  * [x] JSON
  * Recommend incorporating this into https://github.com/frictionlessdata/frictionless-py or https://github.com/frictionlessdata/frictionless-js
* [ ] Support multiple profiles (i.e. being passed a profile)

```python=
# Mandatory Fields

# lowercase alphanumeric and underscores only
name = 'sample_r_dataset2'

# display name
title = 'Sample R Dataset'

notes = 'Detailed Dataset Description'

maintainer='Dataset Maintainer Name'

maintainer_email='Dataset.Maintainer@xxx.org'

publisher='Dataset Publisher'

owner_org='yyy'

visibility='public'
# other options: 'private'

geographic_level='global'
#other options: 'national','regional','sub-national','other'

license_id='notspecified'

information_classification= 'public-public-external'
# other options: 'not_sensitive-non_confidential-internal-business', 'not_sensitive-non_confidential-internal-business', etc
```

## Tasks

* [x] Auto generate a template file in Python
* [x] do this in R
* [x] do this in JS
* [ ] Support multiple profiles

**Comment by rufuspollock** [comment]
@cuducos what does support multiple profiles mean here? If something substantive suggest we move to its own issue and close this.

**Comment by cuducos** [comment]
> what does support multiple profiles mean here? 

TBH, I cannot recall ATM. I think we can close this since the need expressed in other related issues are covered I guess.

**Comment by rufuspollock** [comment]
FIXED. (a long while ago).
