### ISSUE TITLE
Pattern for CKAN Client libraries plus update examples in client guide to 

### ISSUE THREAD

**Issue by rufuspollock** [datopian/tech.datopian.com#23]
Could maybe put this in `/ckan-client-guide/design/` or just direct in the main page ...

## Acceptance

* [x] Have standard outline of an API in https://tech.datopian.com/ckan-client-guide/ **ANS #24**
* [x] Update examples in client guide to reflect this **ANS #24**
  * [ ] BONUS: get fancy and have a switcher between different languages 😉  (FUTURE)
* [x] Link to JS and Python guides **ANS #24**

## Analysis

# Draft

See also https://github.com/datopian/ckan-client-js README and API Guide (though major change in definition of Dataset.create and push)

### Frictionless by Default

The client SHOULD use Frictionless formats by default for describing dataset and resource objects passed to client methods.

In addition, where more than metadata is needed we expect the Dataset and Resource object to follow the Frictionless Data Lib pattern https://github.com/frictionlessdata/project/blob/master/rfcs/0004-frictionless-data-lib-pattern.md

> Internally we then use the CKAN<=>Frictionless Mapper to convert to CKAN formats before calling the API. Thus, you can use Frictionless Formats by default with the client. (As CKAN moves to Frictionless to default this will gradually become unnecessary).

NB: to get Frictionless objects from files we recommend using `data.js` for JS and frictionless-py (?) for python.

### Blob Storage

For blob storage we assume CKAN has adopted the v3 approach with direct to cloud storage supported: http://tech.datopian.com/blob-storage/#direct-to-cloud-upload

## Client

```javascript=
client = Client(...) 
```

### Action API

```
client.action(...)
```

### Storage

e.g. getting authz, interaction with giftless etc

### Porcelain

Dataset

* `create(datasetMetadata, metadataOnly=false)`: iterate through the resources pushing the data for each one then push the dataset metadata
* `push(datasetMetadata)`: ditto but for existing dataset
* `retrieve(datasetIdOrName)`

Resource

* `pushBlob`
* `createResource(resourceObject, datasetIdOrName)`
* `pushResource(resourceObject)`

Also provide example of creating a dataset from a single file ... ACTUALLY THIS SHOULD NOT HAPPEN. Always explicitly create the dataset.

**Comment by cuducos** [comment]
Regarding the switcher for different language snippets, any pros or cons of using a solution like [`vuepress-tabs`](https://github.com/pskordilakis/vuepress-tabs)?

**Comment by rufuspollock** [comment]
sounds good - i would only wonder whether we want to bother for now (e.g.
there are issues about where we source snippets from that are much bigger -
do they come from source client repo (preferable) or locally (risk of
getting out of sync)). For me just having python then js example is ok (or
even just having python for now).


_________________________________________________________________________
*Datopian *| https://datopian.com | Open solutions for a data driven world
*DataHub*  | https://datahub.io   | GitHub for data
*CKAN    * | http://ckan.org <https://ckan.org/>      | The world's leading
data portal solution

President - +44 7795176976 - @rufuspollock

**Comment by cuducos** [comment]
> I would only wonder whether we want to bother for now (e.g.
> there are issues about where we source snippets from that are much bigger

Totally agree.
Updated the opening comment.
I vote to close this issue for now, since the only thing missing is minor importance.

**Comment by rufuspollock** [comment]
FIXED.
