### ISSUE TITLE
Roadmap: CKAN Enterprise

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/tech.datopian.com#31]
When investing time/budget into Datopian Products (CKAN Enterprise), I want to have a roadmap for the year so that I can understand:

- what our goals are
- what we are trying to achieve in the year
- how much we should/can invest

## Acceptance criteria

* [x] I have detailed information about CKAN Enterprise vision/plan at https://tech.datopian.com/ckan-enterprise/
* [x] I have a roadmap at https://tech.datopian.com/ckan-enterprise/

## Tasks

* [x] List what would we like to have/achieve for the project in 2021 and maybe beyond (2022 etc.)
* [x] Describe each feature so that other Datopians can understand
* [x] Based on that create a roadmap for 2021
