### ISSUE TITLE
Roadmap: DataHub Next (v3)

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/tech.datopian.com#32]
When investing time/budget into Datopian Products (DataHub Next), I want to have a roadmap for the year so that I can understand:

- what our goals are
- what we are trying to achieve in the year
- how much we should/can invest

## Acceptance criteria

* [ ] I have information about DataHub Next at https://tech.datopian.com/datahub-next
* [ ] I can understand our near term (2021) goals / roadmap by reading https://tech.datopian.com/datahub-next

## Tasks

* [ ] Create a list of features / hypotheses / ideas we are going to create / test etc.
* [ ] Based on that create a roadmap for 2021
